### ISSUE TITLE
Support for zhimi.fan.za3

### ISSUE THREAD

**Issue by spacecakes** [YinHangCode/homebridge-mi-fan#9]
This, sold as the[ Smartmi Fan 2](https://www.mi-store.se/en/mi-smart-home/xiaomi-smartmi-fan-2s), seems to be yet another version of the Xiaomi fan. Any change we may see support for it in a future version?

**Comment by CooperCGN** [comment]
I got it running by configuring it as a natural wind fan. Only thing is that it shows a humidity sensor with 0% and as I have the battery version there is no battery status visible. Otherwise speed, oscillation and natural wind works without problems.

**Comment by spacecakes** [comment]
Interesting. I didn’t. Got a lot of errors in the console no matter which model I chose. I’m gonna try again.

**Comment by CooperCGN** [comment]
Is your token correct? I had to go that complicated way by making a backup of my iPhone and then extracting the token from there.

**Comment by spacecakes** [comment]
I got one by reseting the fan and using that cli tool. Not sure if it's correct.

**Comment by CooperCGN** [comment]
Most probably not, I had to follow the steps listed here
https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md#non-jailbroken-ios-users

That’s how I got my two Smartmi humidifiers working too. It sounds a bit complicated but if you follow every step closely you should have the correct token in the end.

**Comment by spacecakes** [comment]
Thanks, I will try that. Did you need to configure anything else, like switching any of the booleans to true?

**Comment by CooperCGN** [comment]
I set all sensors to false as I have other devices providing those values. I am not even sure if the fan provides humidity and temperature.

**Comment by spacecakes** [comment]
Got it working! Thank you so much. You were right about the token not being correct. After following the guide, it's now working.

**Comment by CooperCGN** [comment]
Sorry, I have to open this again. When you go into the fan details in HomeKit, do you get a "current humidity" value of 0% too?

**Comment by mszf** [comment]
None of those fans can show humidity or temperature because there is no such sensors build in them. In HomeKit you can always use external sensors together with those fans in automations.
Some of them has build-in battery but battery value is always 0. Don't know if those fans reports status for charging or current battery charge at all or if this is only a plugin issue,

**Comment by CooperCGN** [comment]
Thanks, I was actually aware of the fact that they do not have the sensors, they also do not show any battery level in the Mi home app. That's why I opened another issue for this maybe to get rid of that 0% percent value, even if it is only for optical reasons. My girlfriend already asked me why it shows 0% percent and was thinking it is broken. :)
